#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
[package]
name = "zenoh_backend_influxdb"
version = "0.5.0-beta.9"
authors = ["kydos <angelo@icorsaro.net>",
           "Julien Enoch <julien@enoch.fr>",
           "Olivier Hécart <olivier.hecart@adlinktech.com>",
		   "Luca Cominardi <luca.cominardi@adlinktech.com>"]
edition = "2018"

[lib]
name = "zbackend_influxdb"
crate-type = ["cdylib"]

[dependencies]
zenoh_backend_traits = "0.5.0-beta.9"
zenoh = "0.5.0-beta.9"
zenoh-util = "0.5.0-beta.9"
async-std = "=1.9.0"
async-trait = "0.1.42"
lazy_static = "1.4.0"
regex = "1"
env_logger = "0.8.2"
log = "0.4"
git-version = "0.3.4"
uuid = { version = "0.8.2", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
influxdb = { version = "0.4", default-features = false, features = ["derive", "use-serde", "h1-client-rustls"] }

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.deb]
name = "zenoh-backend-influxdb"
maintainer = "zenoh-dev@eclipse.org"
copyright = "2017, 2020 ADLINK Technology Inc."
section = "net"
license-file = ["LICENSE", "0"]
depends = "zenoh-storages (=0.5.0-beta.9)"